server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userDb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

    flyway:
      url: jdbc:postgresql://localhost:5432/userDb
      user: postgres
      password: 12345
      baseline-on-migrate: true
      locations: classpath:db/migration/user

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
