server:
  port: 9011


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commonBase
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

    flyway:
      url: jdbc:postgresql://localhost:5432/commonBase
      user: postgres
      password: 12345
      baseline-on-migrate: true
      locations: classpath:db/migration/common

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true